First define pauli matrices

In [1]:
import numpy as np  #import the numpy package

sigma_x = np.array([[0, 1],[ 1, 0]])    #define sigma_x
sigma_y = np.array([[0, -1j],[1j, 0]])  #define sigma_y
sigma_z = np.array([[1, 0],[0, -1]])    #define sigma_z

Next create a function to calcuate the commutators for 3 matrices  [sigma_i,sigma_j]

In [5]:
def commutator(a,b):              #deffine commutator operation in a function.
    comm = np.dot(a,b)-np.dot(b,a)
    return comm

Then create a function to calcuate the anti-commutators for 3 matrices {sigma_i,sigma_j}

In [6]:
def anticommutator(a,b):                #deffine anticommutator operation in a function.
    anti_comm = np.dot(a,b)+np.dot(b,a)
    return anti_comm

Next print the values using the commutator function

In [7]:
print(commutator(sigma_x,sigma_y))      #print the value of [sigma_x,sigma_y]
print("      ")

print(commutator(sigma_x,sigma_z))      #print the value of [sigma_x,sigma_z]
print("      ")

print(commutator(sigma_y,sigma_z))      #print the value of [sigma_y,sigma_z]
print("      ")

print(commutator(sigma_y,sigma_x))      #print the value of [sigma_y,sigma_x]
print("      ")

print(commutator(sigma_z,sigma_x))      #print the value of[sigma_z,sigma_x]
print("      ")

print(commutator(sigma_z,sigma_y))      #print the value of[sigma_z,sigma_y]
print("      ")

print(commutator(sigma_x,sigma_x))      #print the value of [sigma_x,sigma_x]
print("      ")

print(commutator(sigma_y,sigma_y))      #print the value of [sigma_y,sigma_y]
print("      ")

print(commutator(sigma_z,sigma_z))      #print the value of [sigma_z,sigma_z]

[[ 0.+2.j  0.+0.j]
 [ 0.+0.j  0.-2.j]]
      
[[ 0 -2]
 [ 2  0]]
      
[[ 0.+0.j  0.+2.j]
 [ 0.+2.j  0.+0.j]]
      
[[ 0.-2.j  0.+0.j]
 [ 0.+0.j  0.+2.j]]
      
[[ 0  2]
 [-2  0]]
      
[[ 0.+0.j  0.-2.j]
 [ 0.-2.j  0.+0.j]]
      
[[0 0]
 [0 0]]
      
[[ 0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j]]
      
[[0 0]
 [0 0]]


After that print the values using using anticommutator function

In [8]:
print(anticommutator(sigma_x,sigma_y))      #print the value of {sigma_x,sigma_y}
print("      ")

print(anticommutator(sigma_x,sigma_z))      #print the value of {sigma_x,sigma_z}
print("      ")

print(anticommutator(sigma_y,sigma_z))      #print the value of {sigma_y,sigma_z}
print("      ")

print(anticommutator(sigma_y,sigma_x))      #print the value of {sigma_y,sigma_x}
print("      ")

print(anticommutator(sigma_z,sigma_x))      #print the value of {sigma_z,sigma_x}
print("      ")

print(anticommutator(sigma_z,sigma_y))      #print the value of {sigma_z,sigma_y}
print("      ")

print(anticommutator(sigma_x,sigma_x))      #print the value of {sigma_x,sigma_x}
print("      ")

print(anticommutator(sigma_y,sigma_y))      #print the value of {sigma_y,sigma_y}
print("      ")

print(anticommutator(sigma_z,sigma_z))      #print the value of {sigma_z,sigma_z}

[[ 0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j]]
      
[[0 0]
 [0 0]]
      
[[ 0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j]]
      
[[ 0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j]]
      
[[0 0]
 [0 0]]
      
[[ 0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j]]
      
[[2 0]
 [0 2]]
      
[[ 2.+0.j  0.+0.j]
 [ 0.+0.j  2.+0.j]]
      
[[2 0]
 [0 2]]


Finally calculate the eignevalues for three pauli matrices

In [9]:
np.linalg.eigvals(sigma_x) #compute eigenvalues of sigma_x

array([ 1., -1.])

In [10]:
np.linalg.eigvals(sigma_y) #compute eigenvalues of sigma_y

array([ 1.+0.j, -1.+0.j])

In [11]:
np.linalg.eigvals(sigma_z) #compute eigenvalues of sigma_z

array([ 1., -1.])