In [1]:
import numpy as np

In [2]:
R = np.array([[np.cos(np.pi/3),-np.sin(np.pi/3),0],[np.sin(np.pi/3),np.cos(np.pi/3),0],[0,0,1]])

In [3]:
print(R)

[[ 0.5       -0.8660254  0.       ]
 [ 0.8660254  0.5        0.       ]
 [ 0.         0.         1.       ]]


In [4]:
a=np.dot(R,R)
b=np.dot(a,R)
c=np.dot(b,R)
d=np.dot(c,R)
e=np.dot(d,R)

In [5]:
print(e)

[[  1.00000000e+00   8.88178420e-16   0.00000000e+00]
 [ -8.88178420e-16   1.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00]]


In [11]:

a=np.array([[1,0,0],[0,1,0],[0,0,1]])
for i in range(6):
     a=np.dot(a,R)


In [12]:
print(a)

[[  1.00000000e+00   8.88178420e-16   0.00000000e+00]
 [ -8.88178420e-16   1.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00]]
