In [4]:
import numpy as np

sigma_x = np.array([[0, 1],[ 1, 0]])
sigma_y = np.array([[0, -1j],[1j, 0]])
sigma_z = np.array([[1, 0],[0, -1]])

a=np.dot(sigma_x,sigma_y)-np.dot(sigma_y,sigma_x)
b=np.dot(sigma_x,sigma_z)-np.dot(sigma_z,sigma_x)
c=np.dot(sigma_y,sigma_z)-np.dot(sigma_z,sigma_y)


d=np.dot(sigma_y,sigma_x)-np.dot(sigma_x,sigma_y)
e=np.dot(sigma_z,sigma_x)-np.dot(sigma_x,sigma_z)
f=np.dot(sigma_z,sigma_y)-np.dot(sigma_y,sigma_z)

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

np.linalg.eigvals(sigma_x)
np.linalg.eigvals(sigma_y)
np.linalg.eigvals(sigma_z)



[[ 0.+2.j  0.+0.j]
 [ 0.+0.j  0.-2.j]]
[[ 0 -2]
 [ 2  0]]
[[ 0.+0.j  0.+2.j]
 [ 0.+2.j  0.+0.j]]
[[ 0.-2.j  0.+0.j]
 [ 0.+0.j  0.+2.j]]
[[ 0  2]
 [-2  0]]
[[ 0.+0.j  0.-2.j]
 [ 0.-2.j  0.+0.j]]


array([ 1., -1.])

In [5]:
def commuator(a,b):
    comm = np.dot(a,b)-np.dot(b,a)
    return comm

In [6]:
print(commuator(sigma_x,sigma_y))

[[ 0.+2.j  0.+0.j]
 [ 0.+0.j  0.-2.j]]
