In [13]:
import numpy as np
from numpy.linalg import inv

a=np.array([[1],[2],[3]])
print(a)

[[1]
 [2]
 [3]]


In [20]:
R=([0, -1, 0],[1, 0, 0],[0, 0, 1])
print(R)

([0, -1, 0], [1, 0, 0], [0, 0, 1])


In [21]:
print(np.dot(R,a))

[[-2]
 [ 1]
 [ 3]]


In [22]:
b=inv(R)

In [25]:
print(np.dot(R,b))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [24]:
print(R)

([0, -1, 0], [1, 0, 0], [0, 0, 1])
